import { ArrowDownUp, ExternalLink } from "lucide-react";
import { formatScore } from "../utils/formatScore";
import type { EnrichedResult, SortKey, SortState } from "../utils/types";
import { MetricBadge } from "./MetricBadge";

type LeaderboardTableProps = {
  results: EnrichedResult[];
  sortState: SortState;
  onSort: (key: SortKey) => void;
};

const metricTooltips: Record<string, string> = {
  character: "Character-level edit scoring. Do not compare directly with word-level F0.5.",
  word: "Word-level edit scoring. Segmentation choices can affect the score.",
  span: "Span-level edit scoring, often generated by ChERRANT for CGEC.",
  unknown: "The survey table reports the score, but the exact unit still needs original-paper verification.",
  official: "Shared-task official score. Keep separate from F0.5 and F1 rows.",
  diagnosis: "Detection or correction diagnostic metric, not a full sentence-rewriting leaderboard score.",
};

export function LeaderboardTable({ results, sortState, onSort }: LeaderboardTableProps) {
  if (results.length === 0) {
    return (
      <div className="empty-state">
        No rows match the current filters.
      </div>
    );
  }

  return (
    <div className="table-shell">
      <table>
        <thead>
          <tr>
            <SortableHeader active={sortState.key === "rank"} label="Rank" onClick={() => onSort("rank")} />
            <SortableHeader active={sortState.key === "paper"} label="Paper / System" onClick={() => onSort("paper")} />
            <SortableHeader active={sortState.key === "year"} label="Year" onClick={() => onSort("year")} />
            <SortableHeader active={sortState.key === "method"} label="Method Family" onClick={() => onSort("method")} />
            <th>Variant</th>
            <SortableHeader active={sortState.key === "metric"} label="Metric" onClick={() => onSort("metric")} />
            <SortableHeader active={sortState.key === "unit"} label="Unit" onClick={() => onSort("unit")} />
            <th>Scorer</th>
            <SortableHeader active={sortState.key === "score"} label="Score" onClick={() => onSort("score")} />
            <th>Source</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          {results.map((result) => (
            <tr className={result.isBestInGroup ? "best-row" : ""} key={result.id}>
              <td className="rank-cell">
                {result.rank ?? "-"}
                {result.isBestInGroup ? <span className="best-marker">best</span> : null}
              </td>
              <td className="paper-cell">
                <strong>{result.paper.citation}</strong>
                <span>{result.system_name}</span>
                {result.paper.paper_url ? (
                  <a href={result.paper.paper_url} rel="noreferrer" target="_blank">
                    Paper <ExternalLink size={13} />
                  </a>
                ) : null}
              </td>
              <td>{result.paper.year}</td>
              <td>
                <MetricBadge label={result.method_family} tone="model" />
              </td>
              <td>{result.model_variant || "-"}</td>
              <td>
                <MetricBadge label={result.metric} tone="metric" />
              </td>
              <td>
                <MetricBadge
                  label={result.unit}
                  tone={result.unit === "unknown" ? "warning" : "unit"}
                  title={metricTooltips[result.unit]}
                />
              </td>
              <td>
                <MetricBadge
                  label={result.scorer}
                  tone={result.scorer === "unknown" ? "warning" : "scorer"}
                />
              </td>
              <td className="score-cell">{formatScore(result.score, result.score_display)}</td>
              <td className="source-cell">
                <span>{result.source}</span>
                <small>{result.source_quote_or_page}</small>
              </td>
              <td className="notes-cell">{result.notes || "-"}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

type SortableHeaderProps = {
  active: boolean;
  label: string;
  onClick: () => void;
};

function SortableHeader({ active, label, onClick }: SortableHeaderProps) {
  return (
    <th>
      <button className={`table-sort ${active ? "is-active" : ""}`} onClick={onClick} type="button">
        {label}
        <ArrowDownUp size={13} aria-hidden="true" />
      </button>
    </th>
  );
}
